### ISSUE TITLE
volo-build parse hive metastore thrift files failed

### ISSUE THREAD

**Issue by Xuanwo** [cloudwego/volo#270]
### Version

volo-build: `0.8.5`

### Platform

No related.

### Crates

volo-build

### Description

volo-build parse [hive metastore thrift files](https://github.com/Xuanwo/hive_metastore_rs/blob/main/thrift_idl/hms.thrift) failed:

```shell
:) cargo +nightly build
   Compiling hive_metastore v0.0.1 (/home/xuanwo/Code/xuanwo/hive_metastore_rs)
error: failed to run custom build command for `hive_metastore v0.0.1 (/home/xuanwo/Code/xuanwo/hive_metastore_rs)`

Caused by:
  process didn't exit successfully: `/home/xuanwo/Code/xuanwo/hive_metastore_rs/target/debug/build/hive_metastore-a5b404aa2f23a9f2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pilota-build-0.9.10/src/parser/thrift/mod.rs:34:53:
  called `Result::unwrap()` on an `Err` value: Error(Error { input: "throws(1:AlreadyExistsException o1,\n        NoSuchObjectException o2, 3:MetaException o3)\n  void alter_ischema(1:AlterISchemaRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  ISchema get_ischema(1:ISchemaName name) throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  void drop_ischema(1:ISchemaName name)\n        throws(1:NoSuchObjectException o1, 2:InvalidOperationException o2, 3:MetaException o3)\n\n  void add_schema_version(1:SchemaVersion schemaVersion)\n        throws(1:AlreadyExistsException o1, 2:NoSuchObjectException o2, 3:MetaException o3)\n  SchemaVersion get_schema_version(1: SchemaVersionDescriptor schemaVersion)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  SchemaVersion get_schema_latest_version(1: ISchemaName schemaName)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  list<SchemaVersion> get_schema_all_versions(1: ISchemaName schemaName)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  void drop_schema_version(1: SchemaVersionDescriptor schemaVersion)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  FindSchemasByColsResp get_schemas_by_cols(1: FindSchemasByColsRqst rqst)\n        throws(1:MetaException o1)\n  // There is no blanket update of SchemaVersion since it is (mostly) immutable.  The only\n  // updates are the specific ones to associate a version with a serde and to change its state\n  void map_schema_version_to_serde(1: MapSchemaVersionToSerdeRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  void set_schema_version_state(1: SetSchemaVersionStateRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:InvalidOperationException o2, 3:MetaException o3)\n\n  void add_serde(1: SerDeInfo serde) throws(1:AlreadyExistsException o1, 2:MetaException o2)\n  SerDeInfo get_serde(1: GetSerdeRequest rqst) throws(1:NoSuchObjectException o1, 2:MetaException o2)\n\n  LockResponse get_lock_materialization_rebuild(1: string dbName, 2: string tableName, 3: i64 txnId)\n  bool heartbeat_lock_materialization_rebuild(1: string dbName, 2: string tableName, 3: i64 txnId)\n\n  void add_runtime_stats(1: RuntimeStat stat) throws(1:MetaException o1)\n  list<RuntimeStat> get_runtime_stats(1: GetRuntimeStatsRequest rqst) throws(1:MetaException o1)\n}\n\n// * Note about the DDL_TIME: When creating or altering a table or a partition,\n// if the DDL_TIME is not set, the current time will be used.\n\n// For storing info about archived partitions in parameters\n\n// Whether the partition is archived\nconst string IS_ARCHIVED = \"is_archived\",\n// The original location of the partition, before archiving. After archiving,\n// this directory will contain the archive. When the partition\n// is dropped, this directory will be deleted\nconst string ORIGINAL_LOCATION = \"original_location\",\n\n// Whether or not the table is considered immutable - immutable tables can only be\n// overwritten or created if unpartitioned, or if partitioned, partitions inside them\n// can only be overwritten or created. Immutability supports write-once and replace\n// semantics, but not append.\nconst string IS_IMMUTABLE = \"immutable\",\n\n// these should be needed only for backward compatibility with filestore\nconst string META_TABLE_COLUMNS   = \"columns\",\nconst string META_TABLE_COLUMN_TYPES   = \"columns.types\",\nconst string BUCKET_FIELD_NAME    = \"bucket_field_name\",\nconst string BUCKET_COUNT         = \"bucket_count\",\nconst string FIELD_TO_DIMENSION   = \"field_to_dimension\",\nconst string META_TABLE_NAME      = \"name\",\nconst string META_TABLE_DB        = \"db\",\nconst string META_TABLE_LOCATION  = \"location\",\nconst string META_TABLE_SERDE     = \"serde\",\nconst string META_TABLE_PARTITION_COLUMNS = \"partition_columns\",\nconst string META_TABLE_PARTITION_COLUMN_TYPES = \"partition_columns.types\",\nconst string FILE_INPUT_FORMAT    = \"file.inputformat\",\nconst string FILE_OUTPUT_FORMAT   = \"file.outputformat\",\nconst string META_TABLE_STORAGE   = \"storage_handler\",\nconst string TABLE_IS_TRANSACTIONAL = \"transactional\",\nconst string TABLE_NO_AUTO_COMPACT = \"no_auto_compaction\",\nconst string TABLE_TRANSACTIONAL_PROPERTIES = \"transactional_properties\",\nconst string TABLE_BUCKETING_VERSION = \"bucketing_version\",\n", code: Tag })
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
hive_metastore_rs on  try-volo [!?] is 📦 v0.0.1 via 🦀 v1.74.0
:( RUST_BACKTRACE=1 cargo +nightly build
   Compiling hive_metastore v0.0.1 (/home/xuanwo/Code/xuanwo/hive_metastore_rs)
error: failed to run custom build command for `hive_metastore v0.0.1 (/home/xuanwo/Code/xuanwo/hive_metastore_rs)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/xuanwo/Code/xuanwo/hive_metastore_rs/target/debug/build/hive_metastore-a5b404aa2f23a9f2/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pilota-build-0.9.10/src/parser/thrift/mod.rs:34:53:
  called `Result::unwrap()` on an `Err` value: Error(Error { input: "throws(1:AlreadyExistsException o1,\n        NoSuchObjectException o2, 3:MetaException o3)\n  void alter_ischema(1:AlterISchemaRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  ISchema get_ischema(1:ISchemaName name) throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  void drop_ischema(1:ISchemaName name)\n        throws(1:NoSuchObjectException o1, 2:InvalidOperationException o2, 3:MetaException o3)\n\n  void add_schema_version(1:SchemaVersion schemaVersion)\n        throws(1:AlreadyExistsException o1, 2:NoSuchObjectException o2, 3:MetaException o3)\n  SchemaVersion get_schema_version(1: SchemaVersionDescriptor schemaVersion)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  SchemaVersion get_schema_latest_version(1: ISchemaName schemaName)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  list<SchemaVersion> get_schema_all_versions(1: ISchemaName schemaName)\n        throws (1:NoSuchObjectException o1, 2:MetaException o2)\n  void drop_schema_version(1: SchemaVersionDescriptor schemaVersion)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  FindSchemasByColsResp get_schemas_by_cols(1: FindSchemasByColsRqst rqst)\n        throws(1:MetaException o1)\n  // There is no blanket update of SchemaVersion since it is (mostly) immutable.  The only\n  // updates are the specific ones to associate a version with a serde and to change its state\n  void map_schema_version_to_serde(1: MapSchemaVersionToSerdeRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:MetaException o2)\n  void set_schema_version_state(1: SetSchemaVersionStateRequest rqst)\n        throws(1:NoSuchObjectException o1, 2:InvalidOperationException o2, 3:MetaException o3)\n\n  void add_serde(1: SerDeInfo serde) throws(1:AlreadyExistsException o1, 2:MetaException o2)\n  SerDeInfo get_serde(1: GetSerdeRequest rqst) throws(1:NoSuchObjectException o1, 2:MetaException o2)\n\n  LockResponse get_lock_materialization_rebuild(1: string dbName, 2: string tableName, 3: i64 txnId)\n  bool heartbeat_lock_materialization_rebuild(1: string dbName, 2: string tableName, 3: i64 txnId)\n\n  void add_runtime_stats(1: RuntimeStat stat) throws(1:MetaException o1)\n  list<RuntimeStat> get_runtime_stats(1: GetRuntimeStatsRequest rqst) throws(1:MetaException o1)\n}\n\n// * Note about the DDL_TIME: When creating or altering a table or a partition,\n// if the DDL_TIME is not set, the current time will be used.\n\n// For storing info about archived partitions in parameters\n\n// Whether the partition is archived\nconst string IS_ARCHIVED = \"is_archived\",\n// The original location of the partition, before archiving. After archiving,\n// this directory will contain the archive. When the partition\n// is dropped, this directory will be deleted\nconst string ORIGINAL_LOCATION = \"original_location\",\n\n// Whether or not the table is considered immutable - immutable tables can only be\n// overwritten or created if unpartitioned, or if partitioned, partitions inside them\n// can only be overwritten or created. Immutability supports write-once and replace\n// semantics, but not append.\nconst string IS_IMMUTABLE = \"immutable\",\n\n// these should be needed only for backward compatibility with filestore\nconst string META_TABLE_COLUMNS   = \"columns\",\nconst string META_TABLE_COLUMN_TYPES   = \"columns.types\",\nconst string BUCKET_FIELD_NAME    = \"bucket_field_name\",\nconst string BUCKET_COUNT         = \"bucket_count\",\nconst string FIELD_TO_DIMENSION   = \"field_to_dimension\",\nconst string META_TABLE_NAME      = \"name\",\nconst string META_TABLE_DB        = \"db\",\nconst string META_TABLE_LOCATION  = \"location\",\nconst string META_TABLE_SERDE     = \"serde\",\nconst string META_TABLE_PARTITION_COLUMNS = \"partition_columns\",\nconst string META_TABLE_PARTITION_COLUMN_TYPES = \"partition_columns.types\",\nconst string FILE_INPUT_FORMAT    = \"file.inputformat\",\nconst string FILE_OUTPUT_FORMAT   = \"file.outputformat\",\nconst string META_TABLE_STORAGE   = \"storage_handler\",\nconst string TABLE_IS_TRANSACTIONAL = \"transactional\",\nconst string TABLE_NO_AUTO_COMPACT = \"no_auto_compaction\",\nconst string TABLE_TRANSACTIONAL_PROPERTIES = \"transactional_properties\",\nconst string TABLE_BUCKETING_VERSION = \"bucketing_version\",\n", code: Tag })
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/a57770440f1ebe5b992551d3bcc489ae211908d4/library/core/src/result.rs:1649:5
     3: core::result::Result<T,E>::unwrap
     4: pilota_build::parser::thrift::parse
     5: <pilota_build::parser::thrift::ParseQuery as salsa::plumbing::QueryFunction>::execute
     6: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
     7: salsa::runtime::Runtime::execute_query_implementation
     8: salsa::derived::slot::Slot<Q,MP>::read_upgrade
     9: salsa::derived::slot::Slot<Q,MP>::read
    10: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
    11: salsa::QueryTable<Q>::try_get
    12: salsa::QueryTable<Q>::get
    13: <DB as pilota_build::parser::thrift::SourceDatabase>::parse::__shim
    14: <DB as pilota_build::parser::thrift::SourceDatabase>::parse
    15: <pilota_build::parser::thrift::ThriftParser as pilota_build::parser::Parser>::parse::{{closure}}
    16: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
    17: <pilota_build::parser::thrift::ThriftParser as pilota_build::parser::Parser>::parse
    18: pilota_build::Builder<MkB,P>::build_cx
    19: pilota_build::Builder<MkB,P>::compile_with_config
    20: volo_build::Builder<MkB,P>::write
    21: build_script_build::main
    22: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Millione** [comment]
It looks like your idl wrote in a wrong way. [It](https://github.com/Xuanwo/hive_metastore_rs/blob/main/thrift_idl/hms.thrift#L2170) should be:
```thrift
2:NoSuchObjectException o2, 3:MetaException o3)
```

**Comment by Xuanwo** [comment]
This IDL is not written by me. It's copied from upstream https://github.com/apache/hive/blob/master/standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift

**Comment by Xuanwo** [comment]
Built with updated thrift files: https://github.com/Xuanwo/hive_metastore_rs/blob/45038dfd00a999d34f43c223390b9c9429dbfb38/thrift_idl/hms.thrift

(we don't need fb303 support, so removed. No other changes.)


```shell
error: failed to run custom build command for `hive_metastore v0.0.1 (/home/xuanwo/Code/xuanwo/hive_metastore_rs)`

Caused by:
  process didn't exit successfully: `/home/xuanwo/Code/xuanwo/hive_metastore_rs/target/debug/build/hive_metastore-a5b404aa2f23a9f2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/xuanwo/Code/xuanwo/hive_metastore_rs/thrift_idl/hms.thrift

  --- stderr
  thread 'main' panicked at /home/xuanwo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pilota-build-0.9.10/src/middle/context.rs:781:18:
  unexpected literal Int(1) with ty U8
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Xuanwo** [comment]
> Update your pilota-build to 0.9.11 version, it should be fixed already.

Perfect!
